--------------------------------------------------------
--  파일이 생성됨 - 금요일-5월-19-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USERS" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"USERPASSWORD" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"USERGENDER" CHAR(1 BYTE), 
	"USERPHONE" VARCHAR2(15 BYTE), 
	"USER_EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
REM INSERTING into SCOTT.USERS
SET DEFINE OFF;
Insert into SCOTT.USERS (USERID,USERPASSWORD,USERNAME,USERGENDER,USERPHONE,USER_EMAIL) values ('admin','admin','admin','m','00000000000','admin@admin.com');
Insert into SCOTT.USERS (USERID,USERPASSWORD,USERNAME,USERGENDER,USERPHONE,USER_EMAIL) values ('user1','user123','유저1','m','01012345679','usesr@gmail.com');
Insert into SCOTT.USERS (USERID,USERPASSWORD,USERNAME,USERGENDER,USERPHONE,USER_EMAIL) values ('user4','user123','유저4','m','01065228544','user444@gmail.com');
Insert into SCOTT.USERS (USERID,USERPASSWORD,USERNAME,USERGENDER,USERPHONE,USER_EMAIL) values ('user2','user123','유저2','w','01012345698','user@gmail.com');
Insert into SCOTT.USERS (USERID,USERPASSWORD,USERNAME,USERGENDER,USERPHONE,USER_EMAIL) values ('user3','user123','유저3','w','01032355678','abc@gmail.com');
--------------------------------------------------------
--  DDL for Index SYS_C007715
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007715" ON "SCOTT"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERGENDER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERPHONE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE"  ENABLE;
