--------------------------------------------------------
--  파일이 생성됨 - 목요일-5월-18-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEAM_AREA
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TEAM_AREA" 
   (	"AREA_NAME" VARCHAR2(4000 BYTE), 
	"AREA_ADDRESS" VARCHAR2(4000 BYTE), 
	"AREA_EXPLANATION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
REM INSERTING into SCOTT.TEAM_AREA
SET DEFINE OFF;
Insert into SCOTT.TEAM_AREA (AREA_NAME,AREA_ADDRESS,AREA_EXPLANATION) values ('휴먼교육센터','충남 천안시 동남구 대흥로 215, 7층, 8층','T.041-561-1122');
Insert into SCOTT.TEAM_AREA (AREA_NAME,AREA_ADDRESS,AREA_EXPLANATION) values ('달식당','충남 천안시 동남구 대흥로 215 백자빌딩 1층 102호 달식당','😋😋돈까스 맛있음!! 친구랑 같이 가서 냉모밀+돈까스 같이 주문해서 노나먹으면 진짜 개꿀맛 👍');
--------------------------------------------------------
--  DDL for Index SYS_C007728
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007728" ON "SCOTT"."TEAM_AREA" ("AREA_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  Constraints for Table TEAM_AREA
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TEAM_AREA" MODIFY ("AREA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TEAM_AREA" MODIFY ("AREA_EXPLANATION" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TEAM_AREA" ADD PRIMARY KEY ("AREA_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE"  ENABLE;
