--여행지

CREATE TABLE team_seoul_01
(
  name VARCHAR2(60) PRIMARY KEY,
  postNum VARCHAR2(10) , 
  address VARCHAR2(90) NOT NULL,
  outline VARCHAR2(4000) ,
  tel VARCHAR2(50),
  opening VARCHAR2(30),
  dayOff VARCHAR2(100) ,
  experienceInfo VARCHAR2(4000),
  experienceAge VARCHAR2(90),
  limitPeople VARCHAR2(100), 
  period VARCHAR2(100) , 
  hours VARCHAR2(900),
  parking VARCHAR2(840) ,
  rentalStroller VARCHAR2(6),
  withPet VARCHAR2(6),
  detailInfo VARCHAR2(4000)
);

ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_NAME TO name;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_POSTNUM TO postNum;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_ADDRESS TO address;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_OUTLINE TO outline;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_TEL TO tel;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_OPENING TO opening;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_DAYOFF TO dayOff;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_EXPERIENCEINFO TO experienceInfo;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_EXPERIENCEAGE TO experienceAge;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_LIMITPEOPLE TO limitPeople;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_PERIOD TO period;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_HOURS TO hours;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_PARKING TO parking;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_RENTALSTROLLER TO rentalStroller;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_WITHPET TO withPet;
ALTER TABLE team_seoul_01 RENAME COLUMN SEOUL_DETAILINFO TO detailInfo;

--DROP TABLE team_seoul_01;
SELECT * FROM team_seoul_01;

SELECT *
FROM team_seoul_01
WHERE seoul_name LIKE '%서울%';
